name: Tests

on:
  pull_request:

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, macos-latest ]
        php-versions: [ 7.4, 8.0, 8.1, 8.2 ]

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-progress

      - name: Execute tests
        run: composer run test:unit
